# nama workflow
name: Deploy Production

# trigger
on:
  push:
    branches:
      - master

# rangkaian perintah
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run production
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: Generate key
        run: php artisan key:generate 
# copy source code ke server menggunakan ssh
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          source: "."
          target: "public_html/apps/"
